In [17]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [18]:
from sklearn.datasets import make_classification
x,y = make_classification(n_samples=1000,n_features=3,n_classes=2,n_redundant=1,random_state=999)
print(x)

[[-0.33504974  0.02852654  1.16193084]
 [-1.37746253 -0.4058213   0.44359618]
 [-1.04520026 -0.72334759 -3.10470423]
 ...
 [-0.75602574 -0.51816111 -2.20382324]
 [ 0.56066316 -0.07335845 -2.15660348]
 [-1.87521902 -1.11380394 -4.04620773]]


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0000)
print(x_test.shape)
print(y_test.shape)

(250, 3)
(250,)


In [20]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()
x_train = s.fit_transform(x_train)
x_test = s.transform(x_test)


In [21]:
from sklearn.neighbors import KNeighborsClassifier
k = KNeighborsClassifier()
k.fit(x_train,y_train)
y_pred = k.predict(x_test)

In [22]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

0.888
[[122   8]
 [ 20 100]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       130
           1       0.93      0.83      0.88       120

    accuracy                           0.89       250
   macro avg       0.89      0.89      0.89       250
weighted avg       0.89      0.89      0.89       250

