In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [3]:
#creating datasets such as standardization is not required
from sklearn.datasets import make_classification
X,Y=make_classification(n_samples=100,n_features=10,n_classes=2,random_state=42)
X = pd.DataFrame(X)
Y

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.30,random_state=42)

In [5]:
from sklearn.linear_model import LogisticRegression
l = LogisticRegression()
l.fit(X_train,Y_train)
y_pred = l.predict(X_test)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1])

In [6]:
l.predict_proba(X_test)

array([[7.49632742e-01, 2.50367258e-01],
       [5.71492961e-02, 9.42850704e-01],
       [8.47383467e-03, 9.91526165e-01],
       [3.84386602e-02, 9.61561340e-01],
       [2.79853023e-02, 9.72014698e-01],
       [9.64640318e-01, 3.53596817e-02],
       [9.65369374e-01, 3.46306260e-02],
       [2.13024820e-01, 7.86975180e-01],
       [2.27546362e-01, 7.72453638e-01],
       [1.81401566e-01, 8.18598434e-01],
       [9.87298049e-01, 1.27019510e-02],
       [1.84390109e-03, 9.98156099e-01],
       [1.11638160e-03, 9.98883618e-01],
       [9.98846835e-01, 1.15316489e-03],
       [3.19528899e-03, 9.96804711e-01],
       [9.75335190e-01, 2.46648100e-02],
       [2.79003416e-02, 9.72099658e-01],
       [9.72840626e-01, 2.71593739e-02],
       [9.57717728e-01, 4.22822718e-02],
       [9.96764165e-01, 3.23583540e-03],
       [3.26255970e-02, 9.67374403e-01],
       [9.91543744e-01, 8.45625612e-03],
       [6.48321099e-01, 3.51678901e-01],
       [9.99581102e-01, 4.18898067e-04],
       [4.128605

In [7]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
s = accuracy_score(y_pred,Y_test)
c = confusion_matrix(y_pred,Y_test)
r = classification_report(y_pred,Y_test)
print(s)
print(c)
print(r)

0.9333333333333333
[[12  0]
 [ 2 16]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.89      0.94        18

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.94      0.93      0.93        30



HYPERPARAMETER TUNING AND CROSS VALIDATION

In [10]:
model = LogisticRegression()
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.1,0.01]
solver = ['newton-cg','lbfgs','liblinear','sag','saga']
params = dict(penalty=penalty,C=c_values,solver=solver)

In [13]:
##Grid Search CV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [14]:
grid.fit(X_train,Y_train)

d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.d

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [18]:
print(grid.best_params_)
print(grid.best_score_)
y_pred2 = grid.predict(X_test)

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}
0.9857142857142858


In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
s2 = accuracy_score(y_pred2,Y_test)
c2 = confusion_matrix(y_pred2,Y_test)
r2 = classification_report(y_pred2,Y_test)
print(s2)
print(c2)
print(r2)

0.9
[[11  0]
 [ 3 16]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        11
           1       1.00      0.84      0.91        19

    accuracy                           0.90        30
   macro avg       0.89      0.92      0.90        30
weighted avg       0.92      0.90      0.90        30



In [ ]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
x = RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy_score',cv=5)
x.fit(X_train,Y_train)
