In [17]:
import matplotlib.pyplot as plt 
import pandas as pd 
import numpy as np 

In [18]:
from sklearn.datasets import load_iris
df=load_iris()
x = pd.DataFrame(df['data'])
y = pd.DataFrame(df['target'])
y

,0
0,0
1,0
2,0
3,0
4,0
...,...
145,2
146,2
147,2
148,2


In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0000)
print(x_test.shape)
print(y_test.shape)

(38, 4)
(38, 1)


In [20]:
from sklearn.tree import DecisionTreeClassifier
d = DecisionTreeClassifier()


In [21]:
params = {
    'criterion':['gini','entropy','log_loss'],
    'splitter':['best','random'],
    'max_depth':[1,2,3,4,5],
    'max_features':['auto','sqrt','log2']
}

In [22]:
from sklearn.model_selection import GridSearchCV
g = GridSearchCV(d,param_grid=params,cv=5,scoring='accuracy')
g.fit(x_train,y_train)
y_pred = g.predict(x_test)

d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
150 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "d:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate

In [23]:
print(g.best_params_)

{'criterion': 'log_loss', 'max_depth': 4, 'max_features': 'log2', 'splitter': 'best'}


In [24]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9736842105263158
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        15
           2       1.00      0.90      0.95        10

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

[[13  0  0]
 [ 0 15  0]
 [ 0  1  9]]
